
const costTrackerType = {
    FETCH_COSTTRACKER_LOADING: 'FETCH_COSTTRACKER_LOADING',
    FETCH_COSTTRACKER_SUCCESS: 'FETCH_COSTTRACKER_SUCCESS',

    FETCH_FUEL_CONSUMPTION_DATA_LOADING: 'FETCH_FUEL_CONSUMPTION_DATA_LOADING',
    FETCH_FUEL_CONSUMPTION_DATA_SUCCESS: 'FETCH_FUEL_CONSUMPTION_DATA_SUCCESS',

    ADD_FUEL_CONSUMPTION_DATA_LOADING: 'ADD_FUEL_CONSUMPTION_DATA_LOADING',
    ADD_FUEL_CONSUMPTION_DATA_SUCCESS: 'ADD_FUEL_CONSUMPTION_DATA_SUCCESS',
    
}

export default costTrackerType;
