
const costTrackerType = {
    FETCH_COSTTRACKER_LOADING: 'FETCH_COSTTRACKER_LOADING',
    FETCH_COSTTRACKER_SUCCESS: 'FETCH_COSTTRACKER_SUCCESS',

    FETCH_FUEL_CONSUMPTION_DATA_LOADING: 'FETCH_FUEL_CONSUMPTION_DATA_LOADING',
    FETCH_FUEL_CONSUMPTION_DATA_SUCCESS: 'FETCH_FUEL_CONSUMPTION_DATA_SUCCESS',

    ADD_FUEL_CONSUMPTION_DATA_LOADING: 'ADD_FUEL_CONSUMPTION_DATA_LOADING',
    ADD_FUEL_CONSUMPTION_DATA_SUCCESS: 'ADD_FUEL_CONSUMPTION_DATA_SUCCESS',

    EDIT_FUEL_CONSUMPTION_DATA_LOADING: 'EDIT_FUEL_CONSUMPTION_DATA_LOADING',
    EDIT_FUEL_CONSUMPTION_DATA_SUCCESS: 'EDIT_FUEL_CONSUMPTION_DATA_SUCCESS',

    DELETE_FUEL_CONSUMPTION_DATA_LOADING: 'DELETE_FUEL_CONSUMPTION_DATA_LOADING',
    DELETE_FUEL_CONSUMPTION_DATA_SUCCESS: 'DELETE_FUEL_CONSUMPTION_DATA_SUCCESS',

    EDIT_FUEL_PURCHASE_DATA_LOADING: 'EDIT_FUEL_PURCHASE_DATA_LOADING',
    EDIT_FUEL_PURCHASE_DATA_SUCCESS: 'EDIT_FUEL_PURCHASE_DATA_SUCCESS',

    DELETE_FUEL_PURCHASE_DATA_LOADING: 'DELETE_FUEL_PURCHASE_DATA_LOADING',
    DELETE_FUEL_PURCHASE_DATA_SUCCESS: 'DELETE_FUEL_PURCHASE_DATA_SUCCESS',
    
    EDIT_PRE_UTILITY_PURCHASE_DATA_LOADING: 'EDIT_PRE_UTILITY_PURCHASE_DATA_LOADING',
    EDIT_PRE_UTILITY_PURCHASE_DATA_SUCCESS: 'EDIT_PRE_UTILITY_PURCHASE_DATA_SUCCESS',

    DELETE_PRE_UTILITY_PURCHASE_DATA_LOADING: 'DELETE_PRE_UTILITY_PURCHASE_DATA_LOADING',
    DELETE_PRE_UTILITY_PURCHASE_DATA_SUCCESS: 'DELETE_PRE_UTILITY_PURCHASE_DATA_SUCCESS',

    EDIT_IPP_PURCHASE_DATA_LOADING: 'EDIT_IPP_PURCHASE_DATA_LOADING',
    EDIT_IPP_PURCHASE_DATA_SUCCESS: 'EDIT_IPP_PURCHASE_DATA_SUCCESS',

    DELETE_IPP_PURCHASE_DATA_LOADING: 'DELETE_IPP_PURCHASE_DATA_LOADING',
    DELETE_IPP_PURCHASE_DATA_SUCCESS: 'DELETE_IPP_PURCHASE_DATA_SUCCESS',
    
    EDIT_POST_UTILITY_PURCHASE_DATA_LOADING: 'EDIT_POST_UTILITY_PURCHASE_DATA_LOADING',
    EDIT_POST_UTILITY_PURCHASE_DATA_SUCCESS: 'EDIT_POST_UTILITY_PURCHASE_DATA_SUCCESS',
    
}

export default costTrackerType;
