
const sidebarType = {
    FETCH_SIDEBAR_LOADING: 'FETCH_SIDEBAR_LOADING',
    FETCH_SIDEBAR_SUCCESS: 'FETCH_SIDEBAR_SUCCESS',
    SET_SELECTED_SIDE_BAR: 'SET_SELECTED_SIDE_BAR'
}

export default sidebarType;