
const BreakerType = {
    FETCH_BREAKER_LOADING: 'FETCH_BREAKER_LOADING',
    FETCH_BREAKER_SUCCESS: 'FETCH_BREAKER_SUCCESS',
    TOGGLE_BREAKER_LOADING: 'TOGGLE_BREAKER_LOADING',
    TOGGLE_BREAKER_SUCCESS: 'TOGGLE_BREAKER_SUCCESS',
}

export default BreakerType;