
const dashBoardType = {
    FETCH_DASHBOARD_LOADING: 'FETCH_DASHBOARD_LOADING',
    FETCH_DASHBOARD_SUCCESS: 'FETCH_DASHBOARD_SUCCESS',
    FETCH_DEMAND_LOADING: 'FETCH_DEMAND_LOADING',
    FETCH_DEMAND_SUCCESS: 'FETCH_DEMAND_SUCCESS',
    FETCH_BLENDEDCOST_ENERGY_LOADING: 'FETCH_BLENDEDCOST_ENERGY_LOADING',
    FETCH_BLENDEDCOST_ENERGY_SUCCESS: 'FETCH_BLENDEDCOST_ENERGY_SUCCESS'
}

export default dashBoardType;